### ISSUE TITLE
Sometimes the UndetectedChromeDriver.builder() is very slow

### ISSUE THREAD

**Issue by safetys123** [bramar2/undetectedselenium#2]
UndetectedChromeDriver driver = UndetectedChromeDriver.builder()
                    .pageLoadStrategy(PageLoadStrategy.NONE)
                    .headless(headless)
                    .driverFromCFT(true)
                    .versionMain(115)
                    .autoOpenDevtools(true)
                    .seleniumStealth(SeleniumStealthOptions.getDefault()).build();
Sometimes  is very slow, especially when my server is low configuration, the method may be execute exceed 5 mins.

**Comment by bramar2** [comment]
The builder() method by default checks the latest version from the web and downloads it (if current driver is outdated). Alternatively, you can use Builder.driverExecutable(path) and Builder.patchProvidedDriver(true)
Here is where all the drivers are stored:
Windows: ~/Appdata/Roaming/java_undetected_chromedriver
Linux: ~/.local/share/java_undetected_chromedriver
Mac/Darwin: ~/Library/Application Support/java_undetected_chromedriver
(If you decide to use the drivers in the folders above, you dont need to use Builder.patchProvidedDriver() since those are already patched)

**Comment by safetys123** [comment]
Thanks for you help, it's more fast than before.
